version: "3.1"

services:
  php:
    image: cakephpserver1
    container_name: mycakeapp-webserver1
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/

  mysql:
    image: mysql:5.7
    container_name: mycakeapp-mysql
    volumes:
      - .:/app
      - ./tmp/data/mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mycakeapp
      MYSQL_USER:  root     
  
  #added phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: mycakeapp-phpmyadmin
    working_dir: /app
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password 